# Generated by Django 5.2.13 on 2026-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, default='jd', max_length=32)),
                ('keyword', models.CharField(max_length=256)),
                ('max_skus', models.PositiveIntegerField(blank=True, null=True)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_to', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('run_dir', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
