# Generated by Django 5.2.13 on 2026-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='cookie_file_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='cookie_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='list_pages',
            field=models.CharField(blank=True, default='', help_text='评论分页，如 "1-2"；空则沿用副本默认', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='pipeline_run_dir',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='pvid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='request_delay',
            field=models.CharField(blank=True, default='', help_text='如 "30-60"；空则沿用副本默认', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='scenario_filter_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
