# Generated by Django 5.2.13 on 2026-04-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_jd_job_dataset_and_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdjobcommentrow',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='jdjobdetailrow',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='jdjobsearchrow',
            name='payload',
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='buy_count_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='comment_date',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='comment_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='comment_score',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='large_pic_urls',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='tag_comment_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobcommentrow',
            name='user_nick_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_belt_banner',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_body_ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_body_ingredients_source_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_brand',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_category_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_csfh_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_delivery_promise',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_main_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_main_sku_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_page_sku_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_price_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_price_original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_product_attributes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_product_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_purchase_price',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_shop_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_shop_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_shop_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_sku_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_sku_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_stock_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_vender_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='http_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='attributes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='comment_count',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='comment_sales_floor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='coupon_price',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='detail_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='hot_list_rank',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='item_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='keyword',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='leaf_category',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='original_price',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='page',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='platform',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='price',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='seckill_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='selling_point',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='shop_info_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='shop_info_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='shop_logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='shop_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='shop_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='uniqpid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jdjobcommentrow',
            name='sku_id',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='jdjobdetailrow',
            name='sku_id',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='jdjobsearchrow',
            name='sku_id',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
