# Generated by Django 5.2.13 on 2026-04-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_job_rows_split_csv_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdJobMergedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('pipeline_keyword', models.TextField(blank=True, default='')),
                ('sku_id', models.TextField(blank=True, db_index=True, default='')),
                ('ware_id', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('price', models.TextField(blank=True, default='')),
                ('coupon_price', models.TextField(blank=True, default='')),
                ('original_price', models.TextField(blank=True, default='')),
                ('selling_point', models.TextField(blank=True, default='')),
                ('hot_list_rank', models.TextField(blank=True, default='')),
                ('comment_fuzzy', models.TextField(blank=True, default='')),
                ('comment_sales_floor', models.TextField(blank=True, default='')),
                ('shop_name', models.TextField(blank=True, default='')),
                ('detail_url', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('attributes', models.TextField(blank=True, default='')),
                ('leaf_category', models.TextField(blank=True, default='')),
                ('keyword', models.TextField(blank=True, default='')),
                ('page', models.TextField(blank=True, default='')),
                ('detail_http_status', models.TextField(blank=True, default='')),
                ('detail_brand', models.TextField(blank=True, default='')),
                ('detail_sku_title', models.TextField(blank=True, default='')),
                ('detail_price_final', models.TextField(blank=True, default='')),
                ('detail_price_original', models.TextField(blank=True, default='')),
                ('detail_shop_name', models.TextField(blank=True, default='')),
                ('detail_category_path', models.TextField(blank=True, default='')),
                ('detail_product_attributes', models.TextField(blank=True, default='')),
                ('detail_main_image', models.TextField(blank=True, default='')),
                ('detail_body_ingredients', models.TextField(blank=True, default='')),
                ('detail_body_ingredients_source_url', models.TextField(blank=True, default='')),
                ('detail_stock_text', models.TextField(blank=True, default='')),
                ('detail_delivery_promise', models.TextField(blank=True, default='')),
                ('comment_http_status', models.TextField(blank=True, default='')),
                ('pipeline_comment_count', models.TextField(blank=True, default='')),
                ('comment_preview', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_merged_rows', to='pipeline.pipelinejob')),
            ],
            options={
                'ordering': ['row_index'],
                'indexes': [models.Index(fields=['job', 'sku_id'], name='pipeline_jd_job_id_830248_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'row_index'), name='uniq_pipeline_jdjobmergedrow_job_idx')],
            },
        ),
    ]
