# Generated by Django 5.2.13 on 2026-04-09 07:37

from django.db import migrations


def _drop_if_column_exists(apps, schema_editor) -> None:
    """列已不存在时跳过（例如旧版 0006 已删过），避免数据库报错。"""
    JdJobMergedRow = apps.get_model("pipeline", "JdJobMergedRow")
    table = JdJobMergedRow._meta.db_table
    conn = schema_editor.connection
    for fname in ("detail_http_status", "comment_http_status"):
        with conn.cursor() as cursor:
            desc = conn.introspection.get_table_description(cursor, table)
        col_names = {d.name for d in desc}
        if fname not in col_names:
            continue
        field = JdJobMergedRow._meta.get_field(fname)
        schema_editor.remove_field(JdJobMergedRow, field)


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_trim_search_detail_merged_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="jdjobmergedrow",
                    name="comment_http_status",
                ),
                migrations.RemoveField(
                    model_name="jdjobmergedrow",
                    name="detail_http_status",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _drop_if_column_exists,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
