# Generated by Django 5.2.13 on 2026-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_repair_jdjobmergedrow_detail_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_brand',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_category_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_price_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_product_attributes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='detail_shop_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
