# Generated by Django 5.2.13 on 2026-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_detail_row_lean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='report_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
