# Generated by Django 5.2.13 on 2026-04-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_pipelinejob_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='cancellation_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已终止')], db_index=True, default='pending', max_length=16),
        ),
    ]
