# Generated by Django 5.2.1 on 2026-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0015_jdjobsearchrow_total_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="jdjobdetailrow",
            name="buyer_ranking_line",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jdjobdetailrow",
            name="buyer_promo_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jdjobmergedrow",
            name="buyer_ranking_line",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jdjobmergedrow",
            name="buyer_promo_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
