# Generated by Django 5.2.1 on 2026-04-16 01:55

from django.db import migrations, models


def backfill_matrix_group_labels(apps, schema_editor):
    from pipeline.matrix_group_label import matrix_group_label_from_detail_path

    JdJobDetailRow = apps.get_model("pipeline", "JdJobDetailRow")
    JdJobMergedRow = apps.get_model("pipeline", "JdJobMergedRow")
    JdJobSearchRow = apps.get_model("pipeline", "JdJobSearchRow")

    chunk: list = []
    for r in JdJobDetailRow.objects.all().iterator(chunk_size=400):
        r.matrix_group_label = matrix_group_label_from_detail_path(
            r.detail_category_path or ""
        )
        chunk.append(r)
        if len(chunk) >= 400:
            JdJobDetailRow.objects.bulk_update(chunk, ["matrix_group_label"])
            chunk.clear()
    if chunk:
        JdJobDetailRow.objects.bulk_update(chunk, ["matrix_group_label"])

    chunk = []
    for r in JdJobMergedRow.objects.all().iterator(chunk_size=400):
        r.matrix_group_label = matrix_group_label_from_detail_path(
            r.detail_category_path or ""
        )
        chunk.append(r)
        if len(chunk) >= 400:
            JdJobMergedRow.objects.bulk_update(chunk, ["matrix_group_label"])
            chunk.clear()
    if chunk:
        JdJobMergedRow.objects.bulk_update(chunk, ["matrix_group_label"])

    sku_to_mg: dict[str, str] = {}
    for r in JdJobMergedRow.objects.exclude(matrix_group_label="").iterator(
        chunk_size=400
    ):
        sk = str(r.sku_id or "").strip()
        if sk:
            sku_to_mg[sk] = r.matrix_group_label

    chunk = []
    for r in JdJobSearchRow.objects.all().iterator(chunk_size=400):
        sk = str(r.sku_id or "").strip()
        r.matrix_group_label = sku_to_mg.get(sk, "")
        chunk.append(r)
        if len(chunk) >= 400:
            JdJobSearchRow.objects.bulk_update(chunk, ["matrix_group_label"])
            chunk.clear()
    if chunk:
        JdJobSearchRow.objects.bulk_update(chunk, ["matrix_group_label"])


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_dataset_browse_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdjobdetailrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由 detail_category_path 解析', max_length=80, verbose_name='报告细类'),
        ),
        migrations.AddField(
            model_name='jdjobmergedrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由 detail_category_path 解析', max_length=80, verbose_name='报告细类'),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由合并表商详路径解析；可按 SKU 从合并表回填', max_length=80, verbose_name='报告细类'),
        ),
        migrations.AddIndex(
            model_name='jdjobdetailrow',
            index=models.Index(fields=['job', 'matrix_group_label'], name='pipeline_jd_job_id_5595d3_idx'),
        ),
        migrations.AddIndex(
            model_name='jdjobmergedrow',
            index=models.Index(fields=['job', 'matrix_group_label'], name='pipeline_jd_job_id_163e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='jdjobsearchrow',
            index=models.Index(fields=['job', 'matrix_group_label'], name='pipeline_jd_job_id_38fae5_idx'),
        ),
        migrations.RunPython(backfill_matrix_group_labels, migrations.RunPython.noop),
    ]
