# Generated by Django 5.2.1 on 2026-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_report_group_matrix_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdjobdetailrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由 detail_category_path 解析', max_length=80, verbose_name='类目'),
        ),
        migrations.AlterField(
            model_name='jdjobmergedrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由 detail_category_path 解析', max_length=80, verbose_name='类目'),
        ),
        migrations.AlterField(
            model_name='jdjobsearchrow',
            name='matrix_group_label',
            field=models.CharField(blank=True, db_index=True, default='', help_text='与 §5 矩阵同源：由合并表商详路径解析；可按 SKU 从合并表回填', max_length=80, verbose_name='类目'),
        ),
    ]
