# Generated by Django 5.2.1 on 2026-04-16 02:13

from django.db import migrations, models


def backfill_volume_sort_fields(apps, schema_editor):
    from pipeline.volume_parse import (
        comment_count_sort_value_from_cell,
        comment_count_sort_value_from_merged,
        sales_sort_value_from_search_cells,
    )

    JdJobSearchRow = apps.get_model("pipeline", "JdJobSearchRow")
    JdJobMergedRow = apps.get_model("pipeline", "JdJobMergedRow")

    chunk: list = []
    for r in JdJobSearchRow.objects.all().iterator(chunk_size=400):
        r.sales_sort_value = sales_sort_value_from_search_cells(
            r.total_sales or "", r.comment_sales_floor or ""
        )
        r.comment_count_sort_value = comment_count_sort_value_from_cell(
            r.comment_count or ""
        )
        chunk.append(r)
        if len(chunk) >= 400:
            JdJobSearchRow.objects.bulk_update(
                chunk, ["sales_sort_value", "comment_count_sort_value"]
            )
            chunk.clear()
    if chunk:
        JdJobSearchRow.objects.bulk_update(
            chunk, ["sales_sort_value", "comment_count_sort_value"]
        )

    chunk = []
    for r in JdJobMergedRow.objects.all().iterator(chunk_size=400):
        r.sales_sort_value = sales_sort_value_from_search_cells(
            r.total_sales or "", r.comment_sales_floor or ""
        )
        r.comment_count_sort_value = comment_count_sort_value_from_merged(
            r.pipeline_comment_count or ""
        )
        chunk.append(r)
        if len(chunk) >= 400:
            JdJobMergedRow.objects.bulk_update(
                chunk, ["sales_sort_value", "comment_count_sort_value"]
            )
            chunk.clear()
    if chunk:
        JdJobMergedRow.objects.bulk_update(
            chunk, ["sales_sort_value", "comment_count_sort_value"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0019_matrix_label_verbose_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdjobmergedrow',
            name='comment_count_sort_value',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='从 pipeline_comment_count 解析，供排序', null=True),
        ),
        migrations.AddField(
            model_name='jdjobmergedrow',
            name='sales_sort_value',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='从 total_sales / 销量楼层解析，供排序', null=True),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='comment_count_sort_value',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='从评价量文案解析，供排序', null=True),
        ),
        migrations.AddField(
            model_name='jdjobsearchrow',
            name='sales_sort_value',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='从 total_sales / 销量楼层解析，供排序', null=True),
        ),
        migrations.AddIndex(
            model_name='jdjobmergedrow',
            index=models.Index(fields=['job', 'sales_sort_value'], name='pipeline_jd_job_id_b59c42_idx'),
        ),
        migrations.AddIndex(
            model_name='jdjobmergedrow',
            index=models.Index(fields=['job', 'comment_count_sort_value'], name='pipeline_jd_job_id_2c9d52_idx'),
        ),
        migrations.AddIndex(
            model_name='jdjobsearchrow',
            index=models.Index(fields=['job', 'sales_sort_value'], name='pipeline_jd_job_id_6798d3_idx'),
        ),
        migrations.AddIndex(
            model_name='jdjobsearchrow',
            index=models.Index(fields=['job', 'comment_count_sort_value'], name='pipeline_jd_job_id_f0aace_idx'),
        ),
        migrations.RunPython(backfill_volume_sort_fields, migrations.RunPython.noop),
    ]
