# Generated by Django 5.2.1 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_search_merged_volume_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='strategy_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
