# Generated by Django 5.2.1 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0021_pipelinejob_strategy_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='semiauto_phase',
            field=models.CharField(blank=True, default='', help_text='半自动任务阶段：browser_open / waiting_login / listening / stopping', max_length=32),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='source_type',
            field=models.CharField(db_index=True, default='auto', help_text='auto=全自动流水线；semiauto=半自动 CDP 监听', max_length=16),
        ),
    ]
